// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I /usr/include/PCSC/ /home/mkungla/howi/workspaces/happy-sdk/sources/nfcsdk/pcsc/const_gen.go

package pcsc

type ScopeType int

const (
	ScardScopeUser     ScopeType = 0x0
	ScardScopeTerminal ScopeType = 0x1
	ScardScopeSystem   ScopeType = 0x2
)
